project 'Demo.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
# Uncomment this line to define a global platform for your project


target 'Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
  
  
  pod 'MJRefresh'

end
